spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db_pet2
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
  flyway:
    clean-disabled: false

  data:
    mongodb:
      database: dp_pet

amazon:
  aws:
    accesskey: